version: '3.5'
services:

  container-status-exporter:
    build: .
    ports:
      - "9777:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

