version: '3.5'
services:

  springboot-exporter:
    build: .
    ports:
      - "9055:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
      SPRINGBOOT_URL: http://10.244.244.150:8080/management/health 
